name: testing github actions

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3
      - name: Hello world
        run: echo "hello world"
        shell: bash
  Good-bye:
    runs-on: ubuntu-latest
    steps:
      - name: Good Bye
        run: echo "Bye bye"
        shell: bash
