name: Tag Trigger

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display tag name
        run: echo "The created tag is ${{ github.ref }}"